name: Scala CI
on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 11

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Initialize Supabase
        run: |
          npx supabase init

      - name: Start Supabase
        run: |
          npx supabase start

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - uses: sbt/setup-sbt@v1

      - name: Create header and run scalafmt
        run: sbt headerCreateAll scalafmtAll

      - name: Build and Test with Coverage
        run: sbt clean coverage test coverageReport coverageAggregate

      - name: Debug Coverage Files
        run: find . -name "scoverage.xml" || echo "No coverage file found"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: eff3ct0/supabase-auth-scala
          files: target/scala-*/scoverage-report/scoverage.xml
          fail_ci_if_error: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-reports

      # Optional: Upload dependency graph
      # - name: Upload dependency graph
      #   uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
