# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI
on:
  pull_request:
  push:
    branches: [ "master" ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Clone Supabase repository
        run: |
          git clone --depth 1 https://github.com/supabase/supabase
          cd supabase/docker
          cp .env.example .env
          docker compose pull

      - name: Start Supabase services
        run: |
          cd supabase/docker
          docker compose up -d
          docker ps

      - name: Wait for Supabase to be ready
        run: sleep 20

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - uses: sbt/setup-sbt@v1

      - name: Create header and run scalafmt
        run: sbt headerCreateAll scalafmtAll

      - name: Build and Test
        run: sbt -v +test

      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
      #- name: Upload dependency graph
      # uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
